Hello World Pgm
Anuhyadasaraju/answcodes pull request #1
Opened 2024-03-07 12:19 UTC by Anuhyadasaraju

2024-03-07 12:26 UTC, ghost reviewed
Please address the comments and update PR.

2024-03-07 12:26 UTC, vbhaskarbe commented on hello_world.py
> +
(1) Add proper header here. like below... follow this for all future programs
#
# A Python Program to print 'Hello, World!' string
# 
# AUTHOR: Anuhya. 7th Mar, 2024
#
(2) Please rename the file as 01_hello_world.py

2024-03-07 12:27 UTC, vbhaskarbe requested changes
Fix comments and update PR again,.

2024-03-07 14:27 UTC, vbhaskarmtech approved these changes

2024-03-08 17:02 UTC, vbhaskarmtech approved these changes

2024-03-08 17:11 UTC, vbhaskarmtech approved these changes

2024-03-10 06:53 UTC, merged